import 'package:sqflite/sqflite.dart';

/// Seeder for payment method types (lookup/reference data)
class PaymentMethodsSeeder {
  static Future<void> seed(Database db) async {
    // Check if already seeded
    final existing = await db.query('payment_method_types', limit: 1);
    if (existing.isNotEmpty) return;

    final paymentMethods = [
      {
        'id': 1,
        'code': 'CASH',
        'name_ar': 'نقدي',
        'name_en': 'Cash',
        'requires_bank': 0,
        'requires_reference': 0,
        'requires_due_date': 0,
        'is_immediate': 1,
        'icon': 'money',
        'color': '#22C55E',
        'sort_order': 1,
        'is_active': 1,
      },
      {
        'id': 2,
        'code': 'BANK_TRANSFER',
        'name_ar': 'حوالة بنكية',
        'name_en': 'Bank Transfer',
        'requires_bank': 1,
        'requires_reference': 1,
        'requires_due_date': 0,
        'is_immediate': 1,
        'icon': 'account_balance',
        'color': '#3B82F6',
        'sort_order': 2,
        'is_active': 1,
      },
      {
        'id': 3,
        'code': 'CHECK',
        'name_ar': 'شيك',
        'name_en': 'Check/Cheque',
        'requires_bank': 1,
        'requires_reference': 1,
        'requires_due_date': 1,
        'is_immediate': 0,
        'icon': 'receipt_long',
        'color': '#F59E0B',
        'sort_order': 3,
        'is_active': 1,
      },
      {
        'id': 4,
        'code': 'CREDIT_CARD',
        'name_ar': 'بطاقة ائتمان',
        'name_en': 'Credit Card',
        'requires_bank': 0,
        'requires_reference': 1,
        'requires_due_date': 0,
        'is_immediate': 1,
        'icon': 'credit_card',
        'color': '#8B5CF6',
        'sort_order': 4,
        'is_active': 1,
      },
      {
        'id': 5,
        'code': 'DEBIT_CARD',
        'name_ar': 'بطاقة مدى',
        'name_en': 'Debit Card (Mada)',
        'requires_bank': 0,
        'requires_reference': 1,
        'requires_due_date': 0,
        'is_immediate': 1,
        'icon': 'payment',
        'color': '#EC4899',
        'sort_order': 5,
        'is_active': 1,
      },
      {
        'id': 6,
        'code': 'CREDIT',
        'name_ar': 'آجل (ذمم)',
        'name_en': 'On Credit (A/R)',
        'requires_bank': 0,
        'requires_reference': 0,
        'requires_due_date': 1,
        'is_immediate': 0,
        'icon': 'schedule',
        'color': '#EF4444',
        'sort_order': 6,
        'is_active': 1,
      },
      {
        'id': 7,
        'code': 'MOBILE_WALLET',
        'name_ar': 'محفظة إلكترونية',
        'name_en': 'Mobile Wallet',
        'requires_bank': 0,
        'requires_reference': 1,
        'requires_due_date': 0,
        'is_immediate': 1,
        'icon': 'phone_android',
        'color': '#06B6D4',
        'sort_order': 7,
        'is_active': 1,
      },
      {
        'id': 8,
        'code': 'INSTALLMENT',
        'name_ar': 'تقسيط',
        'name_en': 'Installment',
        'requires_bank': 0,
        'requires_reference': 0,
        'requires_due_date': 1,
        'is_immediate': 0,
        'icon': 'calendar_month',
        'color': '#14B8A6',
        'sort_order': 8,
        'is_active': 1,
      },
      {
        'id': 9,
        'code': 'POST_DATED_CHECK',
        'name_ar': 'شيك آجل',
        'name_en': 'Post-Dated Check',
        'requires_bank': 1,
        'requires_reference': 1,
        'requires_due_date': 1,
        'is_immediate': 0,
        'icon': 'event',
        'color': '#F97316',
        'sort_order': 9,
        'is_active': 1,
      },
      {
        'id': 10,
        'code': 'PAYMENT_LINK',
        'name_ar': 'رابط دفع',
        'name_en': 'Payment Link',
        'requires_bank': 0,
        'requires_reference': 1,
        'requires_due_date': 0,
        'is_immediate': 1,
        'icon': 'link',
        'color': '#6366F1',
        'sort_order': 10,
        'is_active': 1,
      },
    ];

    for (final method in paymentMethods) {
      await db.insert('payment_method_types', method);
    }
  }
}
